#!/usr/bin/env bash
# First-time setup for Refract. Safe to re-run - every step is idempotent.
#
# What this does:
#   1. Installs packages/core and apps/api (each has its own venv - see
#      docs/DEVELOPMENT.md for why this isn't a unified uv workspace).
#   2. Generates a local encryption key for BYOK API key storage, if one
#      doesn't already exist (apps/api/.env, gitignored).
#   3. Creates and versions the local SQLite database via Alembic - not
#      via the API's own dev-convenience auto-create (see the note below
#      on why that matters).
#   4. Installs the web app's dependencies (pnpm).
#
# No Postgres/Docker required for any of this - SQLite is the default
# (apps/api/src/refract_api/db.py). Postgres is optional; see
# docs/DEVELOPMENT.md's "Running against Postgres instead of SQLite".
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO_ROOT="$(pwd)"

echo "== packages/core =="
cd "$REPO_ROOT/packages/core"
uv sync --all-extras
uv pip install -e . --no-deps

echo
echo "== apps/api =="
cd "$REPO_ROOT/apps/api"
uv sync --all-extras
uv pip install -e . --no-deps

ENV_FILE="$REPO_ROOT/apps/api/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo
  echo "== Generating apps/api/.env (BYOK encryption key) =="
  KEY=$(uv run python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh - gitignored, never commit this file.
# Encrypts workspace BYOK provider API keys at rest (Fernet). Losing this
# key makes every already-saved API key unrecoverable - back it up if this
# stops being a throwaway dev environment.
REFRACT_SETTINGS_ENCRYPTION_KEY=$KEY
EOF
  echo "Wrote $ENV_FILE"
else
  echo
  echo "== apps/api/.env already exists, leaving it as-is =="
fi

echo
echo "== Creating/versioning the local database (Alembic) =="
# Deliberately NOT relying on main.py's own Base.metadata.create_all
# (dev-convenience only, per its own comment) - that path creates tables
# matching current models but never stamps alembic_version, so a later
# `alembic upgrade head` against a create_all-produced DB fails with
# "table already exists" (hit this for real during development - see
# DEV_TRACKER.md). Running the real migrations from an empty/nonexistent
# file avoids that entirely and is what a real deployment does anyway.
set -a
source "$ENV_FILE"
set +a
uv run alembic upgrade head

cd "$REPO_ROOT/apps/web"
echo
echo "== apps/web =="
pnpm install

echo
echo "== Done =="
echo "Next: read docs/TESTING.md's 'first time run' section, or just:"
echo "  Terminal 1: cd apps/api && set -a && source .env && set +a && uv run uvicorn refract_api.main:app --reload"
echo "  Terminal 2: cd apps/web && pnpm dev"
echo "Then open http://localhost:5173"
