"""initial schema

Revision ID: 29fc5ca13ab1
Revises: 
Create Date: 2026-07-10 15:14:16.850548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29fc5ca13ab1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_sets_pipeline_id'), 'benchmark_sets', ['pipeline_id'], unique=False)
    op.create_table('migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('target_model_config', sa.JSON(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('parity_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migrations_pipeline_id'), 'migrations', ['pipeline_id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_pipeline_id'), 'stages', ['pipeline_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('prompt_variant', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_migration_id'), 'candidates', ['migration_id'], unique=False)
    op.create_index(op.f('ix_candidates_stage_id'), 'candidates', ['stage_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('deterministic_checks', sa.JSON(), nullable=False),
    sa.Column('judge_criteria', sa.JSON(), nullable=False),
    sa.Column('downstream_contract', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', name='uq_rubrics_stage_id')
    )
    op.create_index(op.f('ix_rubrics_stage_id'), 'rubrics', ['stage_id'], unique=False)
    op.create_table('stage_dependencies',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_id', 'depends_on_stage_id')
    )
    op.create_table('traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_set_id', sa.Integer(), nullable=False),
    sa.Column('query_index', sa.Integer(), nullable=False),
    sa.Column('is_holdout', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_set_id'], ['benchmark_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_benchmark_set_id'), 'traces', ['benchmark_set_id'], unique=False)
    op.create_table('stage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('rendered_prompt', sa.Text(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('tokens_thinking', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_records_stage_id'), 'stage_records', ['stage_id'], unique=False)
    op.create_index(op.f('ix_stage_records_trace_id'), 'stage_records', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_records_trace_id'), table_name='stage_records')
    op.drop_index(op.f('ix_stage_records_stage_id'), table_name='stage_records')
    op.drop_table('stage_records')
    op.drop_index(op.f('ix_traces_benchmark_set_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_table('stage_dependencies')
    op.drop_index(op.f('ix_rubrics_stage_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_candidates_stage_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_migration_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_stages_pipeline_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_migrations_pipeline_id'), table_name='migrations')
    op.drop_table('migrations')
    op.drop_index(op.f('ix_benchmark_sets_pipeline_id'), table_name='benchmark_sets')
    op.drop_table('benchmark_sets')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
