"""loosen stage record tokens and latency, add documents and metadata

Revision ID: a4cde1332c73
Revises: 0af5f701fe02
Create Date: 2026-07-11 18:14:51.268373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cde1332c73'
down_revision: Union[str, Sequence[str], None] = '0af5f701fe02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-adjusted from the autogenerated version (same reason as
    c201a9fc9be2 / d765c6643d29): SQLite can't ALTER a column's NOT NULL
    constraint, or add a NOT NULL column without a default, in one step -
    both need batch mode (copy-and-move). New NOT NULL JSON columns
    (documents, metadata) get a server_default for the copy step, which is
    then dropped once every existing row has a concrete value, so the
    Python-side model default (list/dict) - not a stale server default -
    governs all future inserts.
    """
    with op.batch_alter_table('pipelines') as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    with op.batch_alter_table('stage_records') as batch_op:
        # tokens_in/tokens_out/tokens_thinking/latency_ms: schema_version 1.1
        # (docs/trace-format.md) makes per-call token/latency accounting
        # optional - "unknown" and "zero" are different things, same
        # reasoning already applied to `cost`.
        batch_op.alter_column('tokens_in', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('tokens_out', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('tokens_thinking', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('latency_ms', existing_type=sa.Float(), nullable=True)
        batch_op.add_column(sa.Column('documents', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('documents', server_default=None)
        batch_op.alter_column('metadata', server_default=None)

    with op.batch_alter_table('stages') as batch_op:
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('metadata', server_default=None)

    with op.batch_alter_table('traces') as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('metadata', server_default=None)


def downgrade() -> None:
    """Downgrade schema.

    Note: re-tightening tokens_in/tokens_out/tokens_thinking/latency_ms back
    to NOT NULL will fail if any row persisted under this revision has a
    NULL value in one of them - that data loss is inherent to reversing a
    nullable relaxation, not something this migration can paper over.
    """
    with op.batch_alter_table('traces') as batch_op:
        batch_op.drop_column('metadata')

    with op.batch_alter_table('stages') as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('system_prompt')

    with op.batch_alter_table('stage_records') as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('documents')
        batch_op.alter_column('latency_ms', existing_type=sa.Float(), nullable=False)
        batch_op.alter_column('tokens_thinking', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('tokens_out', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('tokens_in', existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table('pipelines') as batch_op:
        batch_op.drop_column('category')
