"""add source ids, trace query, and stage record cost

Revision ID: c201a9fc9be2
Revises: 29fc5ca13ab1
Create Date: 2026-07-10 17:05:12.085625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c201a9fc9be2'
down_revision: Union[str, Sequence[str], None] = '29fc5ca13ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-adjusted from the autogenerated version: SQLite can't ALTER a
    # constraint onto an existing table directly (no ALTER CONSTRAINT
    # support), so the unique constraint has to go through batch mode
    # (copy-and-move), same as the column-add on the same table.
    op.add_column('stage_records', sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('stages') as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(length=255), nullable=False, server_default=''))
        batch_op.create_unique_constraint('uq_stages_pipeline_source_id', ['pipeline_id', 'source_id'])
        batch_op.alter_column('source_id', server_default=None)

    with op.batch_alter_table('traces') as batch_op:
        batch_op.add_column(sa.Column('source_trace_id', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('query', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('source_trace_id', server_default=None)
        batch_op.alter_column('query', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('traces') as batch_op:
        batch_op.drop_column('query')
        batch_op.drop_column('source_trace_id')

    with op.batch_alter_table('stages') as batch_op:
        batch_op.drop_constraint('uq_stages_pipeline_source_id', type_='unique')
        batch_op.drop_column('source_id')

    op.drop_column('stage_records', 'cost')
